version: 0.2
phases:
  pre_build:
    commands:
      - pip install --upgrade pip -r requirements.txt .
      - pip uninstall uluru-cli -y
  build:
    commands:
      - ./json_lint --check
      - ./newline_lint --check
      - isort --check-only --verbose --recursive "setup.py" "run_lint" "json_lint" "newline_lint" "uluru/" "tests/"
      - black --check "setup.py" "run_lint" "json_lint" "newline_lint" "uluru/" "tests/"
      - flake8 "setup.py" "run_lint" "json_lint" "newline_lint" "uluru/" "tests/"
      - pylint "setup.py" "run_lint" "json_lint" "newline_lint" "uluru/" "tests/"
      - bandit -r "uluru/" --exclude "tests"
      - pytest --cov="uluru/" --doctest-modules "uluru/" "tests/"
