#!/bin/bash
set -xeuo pipefail
IFS=$'\n\t'

declare -a files=("setup.py" "json_lint" "newline_lint" "src/" "tests/")
./json_lint --check
./newline_lint --check
isort --check-only --verbose --recursive "${files[@]}"
black --check "${files[@]}"
flake8 "${files[@]}"
pylint "${files[@]}"
bandit -r "src/" --exclude "tests"
pytest --cov="src/" --doctest-modules "src/" "tests/" --ignore="src/rpdk/contract"
