#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

echo "--- Automatically fixing up imports using isort ---"
isort -y

echo "--- Linting code with flake8 ---"
flake8 "uluru/" "tests/"

echo "--- Linting code with pylint ---"
pylint "uluru/" "tests/"

echo "--- Running unit tests ---"
pytest "tests/"

echo "PASS"
