AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: "Handler template for the {{ resource_type }} resource type"

Parameters:
  EncryptionKey:
    Type: String
    Description: "The ARN of the key used to encrypt/decrypt requests"
  LambdaRoleArn:
    Type: String
    Description: "The role ARN necessary for the Lambda function to successfully execute"
  LambdaRoleName:
    Type: String
    Description: "The role name necessary for attaching IAM Policy permissions"

Resources:
  LogPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: "CloudWatchLogsPolicy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: "Allow"
          Action:
          - "logs:CreateLogGroup"
          Resource:
            Fn::Sub: "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:*"
        - Effect: "Allow"
          Action:
          - "logs:CreateLogStream"
          - "logs:PutLogEvents"
          Resource:
            Fn::Sub: "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:*"
      Roles:
        - Ref: LambdaRoleName

  ResourceHandler:
    Type: AWS::Serverless::Function
    Properties:
      Description: "Handler lambda function for the {{ resource_type }} resource type"
      KmsKeyArn:
        Ref: EncryptionKey
      Role:
        Ref: LambdaRoleArn
      Timeout: 60
      MemorySize: 256
      {% for key, value in handler_params.items() %}
      {{ key }}: {{ value }}
      {% endfor %}

  CloudFormationPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Ref: ResourceHandler
      Action: lambda:InvokeFunction
      Principal: cloudformation.amazonaws.com

  CloudWatchPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Ref: ResourceHandler
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn:
        Fn::Sub: "arn:aws:events:${AWS::Region}:${AWS::AccountId}:*"

Outputs:
  ResourceHandlerArn:
    Value:
      Fn::GetAtt: ResourceHandler.Arn
